services:
    backend:
        image: 'banurr/midterm'
        container_name: 'midterm_back'
        depends_on:
            - database
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cloudmidterm
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_JPA_SHOW_SQL=true
        ports:
            - 8080:8080
    database:
        image: 'postgres'
        container_name: 'midterm_db'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=cloudmidterm
        ports:
            - 1234:5432
