spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cloudmidterm
        username: postgres
        password: postgres
        hikari:
            auto-commit: false
    servlet:
        multipart:
            max-file-size: 300MB
            max-request-size: 300MB
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8080
